### ISSUE TITLE
Does not play well with retropie

### ISSUE THREAD

**Issue by fiveseven808** [adafruit/Adafruit_Nanoscreen#1]
I know this software is unsupported, but i thought i'd ask anyway in case someone else decides to help me. 

This program works great! Mirroring seems to work really great. I can mirror my console and desktop with ease! However, running emulation station, I run into some hiccups.... and I'm not sure why. If I have an HDMI screen and the oled running at the same time, I noticed the following behavior:

Running emulationstation = fine
Playing games = not fine

To explain the situation more, No matter what emulator I pick, when I select a game to start playing, it goes to the "options" screen, where you can push a button and edit options, and then nanoscreen kind of freezes up. The hdmi monitor is fine and you can continue to play, however nanoscreen continues to run in the background sucking up CPU, not even crashing. 

After killing the process, I am unable to start it back up without rebooting the pi.

If anyone has any ideas, I'm all ears! 

Thanks!

**Comment by PaintYourDragon** [comment]
Possibly something in the retroarch config; it might be set up to change the HDMI output resolution when launching games. This is not the default behavior (it should be keeping the same resolution as in /boot/config.txt) and is a likely source for the nanoscreen problem.

**Comment by fiveseven808** [comment]
I ended up updating the retropie stuff via the built in updated and it started to work! I have no idea what happened. I don't think there were any strange resolutions being set, and if there were, wouldn't it be emulator specific (not affecting the whole of emulationstation)?
