### ISSUE TITLE
Can't open primary display

### ISSUE THREAD

**Issue by Fungie2134** [adafruit/Adafruit_Nanoscreen#2]
```
pi@raspberrypi:~$ sudo nanoscreen
Can't open primary display
pi@raspberrypi:~$

```

How to correct this error ? Right settings are in /boot/config.txt

**Comment by PaintYourDragon** [comment]
What model of Pi, what OS image and revision/date exactly?

**Comment by Fungie2134** [comment]
The last Raspbian OS, a raspberry PI zero.

**Comment by PaintYourDragon** [comment]
Jessie or Jessie Lite?

**Comment by Fungie2134** [comment]
Jessie with Pixel.

**Comment by PaintYourDragon** [comment]
Unable to reproduce; same hardware, same OS. Any other config details you can provide?

**Comment by Fungie2134** [comment]
Yes, I found the problem, when I was flashing a some bit failed to copy and it seem to be the SPI driver, re-wrote and working well now,
